window.WEEK_LISTS = {
  1: [
    { word: "bank", meaning: "銀行" },
    { word: "camp", meaning: "露營" },
    { word: "hand", meaning: "手" },
    { word: "paint", meaning: "油漆；繪畫" },
    { word: "plant", meaning: "植物；種植" },
    { word: "pond", meaning: "池塘" },
    { word: "pump", meaning: "幫浦；抽水" },
    { word: "stamp", meaning: "郵票；蓋章" },
    { word: "stand", meaning: "站立；攤位" },
    { word: "stump", meaning: "樹樁" },
    { word: "wind", meaning: "風" },
    { word: "wink", meaning: "眨眼" },
    { word: "hungry", meaning: "飢餓的" },
    { word: "lapping", meaning: "舔食；拍打（水聲）" },
    { word: "milk", meaning: "牛奶" },
    { word: "quiet", meaning: "安靜的" },
    { word: "television", meaning: "電視" },
    { word: "backyard", meaning: "後院" },
    { word: "basement", meaning: "地下室" },
    { word: "clean", meaning: "清潔" },
    { word: "fly up", meaning: "飛起來" },
    { word: "keep-away", meaning: "躲避；避免靠近" },
    { word: "near", meaning: "靠近" },
    { word: "paint", meaning: "油漆；繪畫" },
    { word: "upstairs", meaning: "樓上" }
  ],
  2: [
    { word: "belt", meaning: "皮帶" },
    { word: "elf", meaning: "小精靈" },
    { word: "gift", meaning: "禮物" },
    { word: "golf", meaning: "高爾夫球" },
    { word: "left", meaning: "左邊" },
    { word: "lift", meaning: "抬起；電梯" },
    { word: "melt", meaning: "融化" },
    { word: "quilt", meaning: "被子" },
    { word: "raft", meaning: "木筏" },
    { word: "shelf", meaning: "書架" },
    { word: "wilt", meaning: "枯萎" },
    { word: "wolf", meaning: "狼" },
    { word: "came", meaning: "來（come 的過去式）" },
    { word: "bait", meaning: "餌" },
    { word: "rake", meaning: "耙子" },
    { word: "hay", meaning: "乾草" },
    { word: "plate", meaning: "盤子" },
    { word: "pail", meaning: "水桶" },
    { word: "cane", meaning: "手杖；甘蔗" },
    { word: "raise", meaning: "舉起；提高" },
    { word: "grape", meaning: "葡萄" },
    { word: "say", meaning: "說" },
    { word: "aid", meaning: "幫助" },
    { word: "pain", meaning: "疼痛" },
    { word: "trail", meaning: "小徑；追蹤" },
    { word: "stain", meaning: "污漬；弄髒" },
    { word: "blaze", meaning: "火焰" },
    { word: "almost", meaning: "幾乎" },
    { word: "dishes", meaning: "碗盤" },
    { word: "everyone", meaning: "每個人" },
    { word: "family", meaning: "家庭" },
    { word: "later", meaning: "之後" },
    { word: "soup", meaning: "湯" },
    { word: "still", meaning: "仍然；安靜的" },
    { word: "together", meaning: "一起" },
    { word: "window", meaning: "窗戶" },
    { word: "children", meaning: "孩子們" },
    { word: "collar", meaning: "衣領" },
    { word: "heel", meaning: "腳跟" },
    { word: "hurt", meaning: "受傷" },
    { word: "in front of", meaning: "在⋯前面" },
    { word: "lean", meaning: "傾斜；靠著" },
    { word: "pet store", meaning: "寵物店" },
    { word: "snort", meaning: "哼鼻子聲；噴氣聲" }
  ],
  3: [
    { word: "scrape", meaning: "刮；擦" },
    { word: "scratch", meaning: "抓；搔" },
    { word: "screen", meaning: "螢幕；幕" },
    { word: "scrub", meaning: "擦洗" },
    { word: "splash", meaning: "濺起；潑水" },
    { word: "split", meaning: "分開；裂開" },
    { word: "sprain", meaning: "扭傷" },
    { word: "spray", meaning: "噴灑" },
    { word: "spring", meaning: "春天；彈簧" },
    { word: "strap", meaning: "皮帶；帶子" },
    { word: "stripes", meaning: "條紋" },
    { word: "strong", meaning: "強壯的" },
    { word: "deep", meaning: "深的" },
    { word: "meal", meaning: "餐點" },
    { word: "sheep", meaning: "綿羊" },
    { word: "each", meaning: "每一個" },
    { word: "wheel", meaning: "輪子" },
    { word: "treat", meaning: "款待；對待" },
    { word: "bean", meaning: "豆子" },
    { word: "seen", meaning: "看見（see 的過去分詞）" },
    { word: "team", meaning: "團隊" },
    { word: "dream", meaning: "夢；夢想" },
    { word: "mean", meaning: "意思是；刻薄的" },
    { word: "leave", meaning: "離開" },
    { word: "cream", meaning: "奶油" },
    { word: "sleep", meaning: "睡覺" },
    { word: "sneeze", meaning: "打噴嚏" },
    { word: "copies", meaning: "複本；份數" },
    { word: "enough", meaning: "足夠的" },
    { word: "library", meaning: "圖書館" },
    { word: "number", meaning: "數字" },
    { word: "prizes", meaning: "獎品" },
    { word: "ribbon", meaning: "緞帶" },
    { word: "ring", meaning: "戒指；鈴聲" },
    { word: "rope", meaning: "繩子" },
    { word: "sign", meaning: "標誌；簽名" },
    { word: "tonight", meaning: "今晚" },
    { word: "happen", meaning: "發生" },
    { word: "miss", meaning: "想念；錯過" },
    { word: "nice", meaning: "好的；親切的" },
    { word: "steps", meaning: "步驟；樓梯" },
    { word: "terrible", meaning: "可怕的；糟糕" }
  ],
  4: [],
  5: [],
  6: [],
  7: [],
  8: [],
  9: [],
  10: [],
  11: [],
  12: [],
  13: [],
  14: [],
  15: [],
  16: [],
  17: [],
  18: []
};