window.WEEK_LISTS = {
  1: [
    { word: "bank", meaning: "銀行" },
    { word: "camp", meaning: "露營" },
    { word: "hand", meaning: "手" },
    { word: "paint", meaning: "油漆；繪畫" },
    { word: "plant", meaning: "植物；種植" },
    { word: "pond", meaning: "池塘" },
    { word: "pump", meaning: "幫浦；抽水" },
    { word: "stamp", meaning: "郵票；蓋章" },
    { word: "stand", meaning: "站立；攤位" },
    { word: "stump", meaning: "樹樁" },
    { word: "wind", meaning: "風" },
    { word: "wink", meaning: "眨眼" },
    { word: "hungry", meaning: "飢餓的" },
    { word: "lapping", meaning: "舔食；拍打（水聲）" },
    { word: "milk", meaning: "牛奶" },
    { word: "quiet", meaning: "安靜的" },
    { word: "television", meaning: "電視" },
    { word: "backyard", meaning: "後院" },
    { word: "basement", meaning: "地下室" },
    { word: "clean", meaning: "清潔" },
    { word: "fly up", meaning: "飛起來" },
    { word: "keep-away", meaning: "躲避；避免靠近" },
    { word: "near", meaning: "靠近" },
    { word: "paint", meaning: "油漆；繪畫" },
    { word: "upstairs", meaning: "樓上" }
  ],

  2: [
    { word: "belt", meaning: "皮帶" },
    { word: "elf", meaning: "小精靈" },
    { word: "gift", meaning: "禮物" },
    { word: "golf", meaning: "高爾夫球" },
    { word: "left", meaning: "左邊" },
    { word: "lift", meaning: "抬起；電梯" },
    { word: "melt", meaning: "融化" },
    { word: "quilt", meaning: "被子" },
    { word: "raft", meaning: "木筏" },
    { word: "shelf", meaning: "書架" },
    { word: "wilt", meaning: "枯萎" },
    { word: "wolf", meaning: "狼" },
    { word: "came", meaning: "來（come 的過去式）" },
    { word: "bait", meaning: "餌" },
    { word: "rake", meaning: "耙子" },
    { word: "hay", meaning: "乾草" },
    { word: "plate", meaning: "盤子" },
    { word: "pail", meaning: "水桶" },
    { word: "cane", meaning: "手杖；甘蔗" },
    { word: "raise", meaning: "舉起；提高" },
    { word: "grape", meaning: "葡萄" },
    { word: "say", meaning: "說" },
    { word: "aid", meaning: "幫助" },
    { word: "pain", meaning: "疼痛" },
    { word: "trail", meaning: "小徑；追蹤" },
    { word: "stain", meaning: "污漬；弄髒" },
    { word: "blaze", meaning: "火焰" },
    { word: "almost", meaning: "幾乎" },
    { word: "dishes", meaning: "碗盤" },
    { word: "everyone", meaning: "每個人" },
    { word: "family", meaning: "家庭" },
    { word: "later", meaning: "之後" },
    { word: "soup", meaning: "湯" },
    { word: "still", meaning: "仍然；安靜的" },
    { word: "together", meaning: "一起" },
    { word: "window", meaning: "窗戶" },
    { word: "children", meaning: "孩子們" },
    { word: "collar", meaning: "衣領" },
    { word: "heel", meaning: "腳跟" },
    { word: "hurt", meaning: "受傷" },
    { word: "in front of", meaning: "在⋯前面" },
    { word: "lean", meaning: "傾斜；靠著" },
    { word: "pet store", meaning: "寵物店" },
    { word: "snort", meaning: "哼鼻子聲；噴氣聲" }
  ],

  3: [
    { word: "scrape", meaning: "刮；擦" },
    { word: "scratch", meaning: "抓；搔" },
    { word: "screen", meaning: "螢幕；幕" },
    { word: "scrub", meaning: "擦洗" },
    { word: "splash", meaning: "濺起；潑水" },
    { word: "split", meaning: "分開；裂開" },
    { word: "sprain", meaning: "扭傷" },
    { word: "spray", meaning: "噴灑" },
    { word: "spring", meaning: "春天；彈簧" },
    { word: "strap", meaning: "皮帶；帶子" },
    { word: "stripes", meaning: "條紋" },
    { word: "strong", meaning: "強壯的" },
    { word: "deep", meaning: "深的" },
    { word: "meal", meaning: "餐點" },
    { word: "sheep", meaning: "綿羊" },
    { word: "each", meaning: "每一個" },
    { word: "wheel", meaning: "輪子" },
    { word: "treat", meaning: "款待；對待" },
    { word: "bean", meaning: "豆子" },
    { word: "seen", meaning: "看見（see 的過去分詞）" },
    { word: "team", meaning: "團隊" },
    { word: "dream", meaning: "夢；夢想" },
    { word: "mean", meaning: "意思是；刻薄的" },
    { word: "leave", meaning: "離開" },
    { word: "cream", meaning: "奶油" },
    { word: "sleep", meaning: "睡覺" },
    { word: "sneeze", meaning: "打噴嚏" },
    { word: "copies", meaning: "複本；份數" },
    { word: "enough", meaning: "足夠的" },
    { word: "library", meaning: "圖書館" },
    { word: "number", meaning: "數字" },
    { word: "prizes", meaning: "獎品" },
    { word: "ribbon", meaning: "緞帶" },
    { word: "ring", meaning: "戒指；鈴聲" },
    { word: "rope", meaning: "繩子" },
    { word: "sign", meaning: "標誌；簽名" },
    { word: "tonight", meaning: "今晚" },
    { word: "happen", meaning: "發生" },
    { word: "miss", meaning: "想念；錯過" },
    { word: "nice", meaning: "好的；親切的" },
    { word: "steps", meaning: "步驟；樓梯" },
    { word: "terrible", meaning: "可怕的；糟糕的" }
  ]
};


  4: [
    { word: "knee", meaning: "膝蓋" },
    { word: "kneel", meaning: "跪下" },
    { word: "knife", meaning: "刀子" },
    { word: "knit", meaning: "編織" },
    { word: "knob", meaning: "門把；旋鈕" },
    { word: "knock", meaning: "敲；打" },
    { word: "knot", meaning: "結" },
    { word: "wrap", meaning: "包裹；包起來" },
    { word: "wreath", meaning: "花圈" },
    { word: "wrench", meaning: "扳手" },
    { word: "wrist", meaning: "手腕" },
    { word: "write", meaning: "寫" },
    { word: "wrong", meaning: "錯的" },
    { word: "shy", meaning: "害羞的" },
    { word: "right", meaning: "正確的；右邊" },
    { word: "wide", meaning: "寬的" },
    { word: "light", meaning: "光；輕的" },
    { word: "pine", meaning: "松樹" },
    { word: "fight", meaning: "打架；奮鬥" },
    { word: "fly", meaning: "飛" },
    { word: "night", meaning: "夜晚" },
    { word: "dry", meaning: "乾的" },
    { word: "sight", meaning: "視力；景象" },
    { word: "might", meaning: "可能；力量" },
    { word: "tight", meaning: "緊的" },
    { word: "stripe", meaning: "條紋" },
    { word: "sly", meaning: "狡猾的" },
    { word: "cry", meaning: "哭" },
    { word: "basket", meaning: "籃子" },
    { word: "bend down", meaning: "彎下腰" },
    { word: "kind", meaning: "親切的；種類" },
    { word: "wave", meaning: "揮手；波浪" },
    { word: "enter", meaning: "進入" },
    { word: "never", meaning: "從不" },
    { word: "picture", meaning: "圖片；照片" },
    { word: "proud", meaning: "驕傲的" },
    { word: "shiny", meaning: "閃亮的" },
    { word: "spray", meaning: "噴灑" }
  ],

  5: [
    { word: "brick", meaning: "磚塊" },
    { word: "check", meaning: "檢查；支票" },
    { word: "chick", meaning: "小雞" },
    { word: "clock", meaning: "時鐘" },
    { word: "duck", meaning: "鴨子" },
    { word: "lock", meaning: "鎖" },
    { word: "pocket", meaning: "口袋" },
    { word: "rack", meaning: "架子" },
    { word: "rock", meaning: "岩石；搖動" },
    { word: "rocket", meaning: "火箭" },
    { word: "snack", meaning: "點心" },
    { word: "thick", meaning: "厚的" },
    { word: "track", meaning: "軌道；跑道" },
    { word: "poke", meaning: "戳；捅" },
    { word: "boat", meaning: "船" },
    { word: "row", meaning: "划船；一排" },
    { word: "goat", meaning: "山羊" },
    { word: "snow", meaning: "雪" },
    { word: "toad", meaning: "蟾蜍" },
    { word: "soap", meaning: "肥皂" },
    { word: "blow", meaning: "吹" },
    { word: "coat", meaning: "外套" },
    { word: "tow", meaning: "拖拉" },
    { word: "coach", meaning: "教練；長途車" },
    { word: "float", meaning: "漂浮" },
    { word: "toast", meaning: "烤麵包；敬酒" },
    { word: "slow", meaning: "慢的" },
    { word: "globe", meaning: "地球儀" },
    { word: "at once", meaning: "立刻" },
    { word: "dog toys", meaning: "狗玩具" },
    { word: "guess", meaning: "猜" },
    { word: "inside", meaning: "裡面" },
    { word: "judge", meaning: "法官；判斷" },
    { word: "place", meaning: "地方" }
  ],

  6: [
    { word: "bright", meaning: "明亮的" },
    { word: "caught", meaning: "抓住（catch 的過去式）" },
    { word: "eight", meaning: "八" },
    { word: "flight", meaning: "飛行；班機" },
    { word: "high", meaning: "高的" },
    { word: "knight", meaning: "騎士" },
    { word: "light", meaning: "光；輕的" },
    { word: "night", meaning: "夜晚" },
    { word: "right", meaning: "正確的；右邊" },
    { word: "sign", meaning: "標誌；簽名" },
    { word: "sight", meaning: "視力；景象" },
    { word: "straight", meaning: "直的" },
    { word: "tight", meaning: "緊的" },
    { word: "tune", meaning: "曲調" },
    { word: "moon", meaning: "月亮" },
    { word: "pool", meaning: "水池" },
    { word: "zoo", meaning: "動物園" },
    { word: "rude", meaning: "粗魯的" },
    { word: "soon", meaning: "很快" },
    { word: "boot", meaning: "靴子" },
    { word: "food", meaning: "食物" },
    { word: "tube", meaning: "管子" },
    { word: "room", meaning: "房間" },
    { word: "moose", meaning: "駝鹿" },
    { word: "goose", meaning: "鵝" },
    { word: "zoom", meaning: "快速移動；放大" },
    { word: "balloon", meaning: "氣球" },
    { word: "shoot", meaning: "射擊" },
    { word: "a can of", meaning: "一罐⋯" },
    { word: "enter", meaning: "進入" },
    { word: "first", meaning: "第一" },
    { word: "glitter", meaning: "閃閃發光" },
    { word: "gold", meaning: "黃金" },
    { word: "prizes", meaning: "獎品" },
    { word: "second", meaning: "第二" },
    { word: "sign up", meaning: "報名" },
    { word: "surely", meaning: "確定地；當然" },
    { word: "third", meaning: "第三" },
    { word: "look at", meaning: "看著" },
    { word: "no cost", meaning: "免費" },
    { word: "nod", meaning: "點頭" },
    { word: "paste", meaning: "黏貼；糊狀物" },
    { word: "permission", meaning: "允許" }
  ]
};


  7: [
    { word: "basement", meaning: "地下室" },
    { word: "bright-eyed", meaning: "目光明亮的；精神奕奕的" },
    { word: "lean", meaning: "傾斜；靠著" },
    { word: "past", meaning: "過去；經過" },
    { word: "wrong", meaning: "錯的" },
    { word: "remember", meaning: "記得" },
    { word: "clap", meaning: "拍手" },
    { word: "crowd", meaning: "人群" },
    { word: "hug", meaning: "擁抱" },
    { word: "nervous", meaning: "緊張的" },
    { word: "people", meaning: "人們" },
    { word: "ring", meaning: "戒指；鈴聲" }
  ],

  8: [
    { word: "different", meaning: "不同的" },
    { word: "hold up", meaning: "舉起；支撐" },
    { word: "lay down", meaning: "躺下" },
    { word: "other", meaning: "其他的" },
    { word: "racehorse", meaning: "賽馬" },
    { word: "win", meaning: "贏" },
    { word: "winner", meaning: "贏家" }
  ],

  9: [
    { word: "what", meaning: "什麼" },
    { word: "clash", meaning: "衝突；撞擊聲" },
    { word: "shock", meaning: "震驚" },
    { word: "while", meaning: "當⋯時候" },
    { word: "shame", meaning: "羞愧" },
    { word: "flash", meaning: "閃光" },
    { word: "where", meaning: "哪裡" },
    { word: "shine", meaning: "發光" },
    { word: "why", meaning: "為什麼" },
    { word: "shore", meaning: "海岸" },
    { word: "shall", meaning: "將要（助動詞）" },
    { word: "share", meaning: "分享" },
    { word: "shadow", meaning: "影子" },
    { word: "whisper", meaning: "耳語；小聲說話" },
    { word: "whiskers", meaning: "鬍鬚（貓或動物）" },
    { word: "different", meaning: "不同的" },
    { word: "hold up", meaning: "舉起；支撐" },
    { word: "lay down", meaning: "躺下" },
    { word: "other", meaning: "其他的" },
    { word: "racehorse", meaning: "賽馬" },
    { word: "win", meaning: "贏" },
    { word: "winner", meaning: "贏家" },
    { word: "braid", meaning: "辮子" },
    { word: "chain", meaning: "鏈子" },
    { word: "hay", meaning: "乾草" },
    { word: "mail", meaning: "郵件" },
    { word: "pail", meaning: "水桶" },
    { word: "paint", meaning: "油漆；繪畫" },
    { word: "pay", meaning: "支付" },
    { word: "rain", meaning: "下雨" },
    { word: "sail", meaning: "航行；帆" },
    { word: "stain", meaning: "污漬；弄髒" },
    { word: "train", meaning: "火車" },
    { word: "tray", meaning: "托盤" },
    { word: "beads", meaning: "珠子" },
    { word: "bean", meaning: "豆子" },
    { word: "beef", meaning: "牛肉" },
    { word: "bread", meaning: "麵包" },
    { word: "head", meaning: "頭" },
    { word: "heel", meaning: "腳跟" },
    { word: "leaf", meaning: "樹葉" },
    { word: "screen", meaning: "螢幕" },
    { word: "seat", meaning: "座位" },
    { word: "steam", meaning: "蒸氣" },
    { word: "thread", meaning: "線" },
    { word: "tree", meaning: "樹" },
    { word: "climb", meaning: "爬" },
    { word: "myself", meaning: "我自己" },
    { word: "practice", meaning: "練習" },
    { word: "track", meaning: "跑道；軌道" },
    { word: "uncle", meaning: "叔叔；舅舅" },
    { word: "whiskers", meaning: "鬍鬚（貓或動物）" }
  ]
};
window.WEEK_LISTS = {
  ...window.WEEK_LISTS,

  10: [
    { word: "braid", meaning: "辮子" },
    { word: "chain", meaning: "鏈子" },
    { word: "hay", meaning: "乾草" },
    { word: "nail", meaning: "指甲；釘子" },
    { word: "pail", meaning: "水桶" },
    { word: "paint", meaning: "油漆；繪畫" },
    { word: "pay", meaning: "支付" },
    { word: "rain", meaning: "下雨" },
    { word: "sail", meaning: "航行；帆" },
    { word: "stain", meaning: "污漬；弄髒" },
    { word: "beads", meaning: "珠子" },
    { word: "bean", meaning: "豆子" },
    { word: "beef", meaning: "牛肉" },
    { word: "bead", meaning: "珠子" },
    { word: "head", meaning: "頭" },
    { word: "heel", meaning: "腳跟" },
    { word: "leaf", meaning: "樹葉" },
    { word: "screen", meaning: "螢幕" },
    { word: "seat", meaning: "座位" },
    { word: "steam", meaning: "蒸氣" },
    { word: "thread", meaning: "線" },
    { word: "tree", meaning: "樹" },
    { word: "climb", meaning: "爬" },
    { word: "myself", meaning: "我自己" },
    { word: "practice", meaning: "練習" },
    { word: "track", meaning: "跑道；軌道" },
    { word: "uncle", meaning: "叔叔；舅舅" },
    { word: "whiskers", meaning: "鬍鬚（貓或動物）" },
    { word: "wrote", meaning: "寫（write 的過去式）" },
    { word: "clover", meaning: "苜蓿" },
    { word: "danger", meaning: "危險" },
    { word: "field", meaning: "田地" },
    { word: "noise", meaning: "噪音" },
    { word: "pass", meaning: "經過；傳遞" },
    { word: "rest", meaning: "休息" },
    { word: "rumble", meaning: "隆隆聲" },
    { word: "sky", meaning: "天空" },
    { word: "thunder", meaning: "雷聲" }
  ],

  11: [
    { word: "blow", meaning: "吹" },
    { word: "bowl", meaning: "碗" },
    { word: "crow", meaning: "烏鴉" },
    { word: "goat", meaning: "山羊" },
    { word: "pillow", meaning: "枕頭" },
    { word: "road", meaning: "道路" },
    { word: "snow", meaning: "雪" },
    { word: "soap", meaning: "肥皂" },
    { word: "throw", meaning: "丟；投" },
    { word: "toad", meaning: "蟾蜍" },
    { word: "toast", meaning: "烤麵包；敬酒" },
    { word: "window", meaning: "窗戶" },
    { word: "bath", meaning: "洗澡" },
    { word: "peach", meaning: "桃子" },
    { word: "tooth", meaning: "牙齒" },
    { word: "thin", meaning: "瘦的；薄的" },
    { word: "choke", meaning: "哽住；窒息" },
    { word: "much", meaning: "許多" },
    { word: "with", meaning: "和；與" },
    { word: "chick", meaning: "小雞" },
    { word: "teach", meaning: "教" },
    { word: "thank", meaning: "感謝" },
    { word: "child", meaning: "孩子" },
    { word: "chore", meaning: "家務" },
    { word: "reach", meaning: "伸手；達到" },
    { word: "thick", meaning: "厚的" },
    { word: "think", meaning: "想；認為" },
    { word: "carrot", meaning: "紅蘿蔔" },
    { word: "cool", meaning: "涼爽的；酷的" },
    { word: "gloves", meaning: "手套" },
    { word: "haircut", meaning: "理髮" },
    { word: "patch", meaning: "補丁；一小塊" },
    { word: "pond", meaning: "池塘" },
    { word: "spring", meaning: "春天；彈簧" },
    { word: "voice", meaning: "聲音" },
    { word: "wool", meaning: "羊毛" },
    { word: "acorn", meaning: "橡實" },
    { word: "angry", meaning: "生氣的" },
    { word: "as fast as", meaning: "像⋯一樣快" },
    { word: "bless", meaning: "祝福" },
    { word: "chattering", meaning: "喋喋不休" },
    { word: "dig", meaning: "挖" },
    { word: "hill", meaning: "小山" },
    { word: "oak", meaning: "橡樹" },
    { word: "squirrel", meaning: "松鼠" },
    { word: "thief", meaning: "小偷" },
    { word: "tiny", meaning: "微小的" }
  ],

  12: [
    { word: "boot", meaning: "靴子" },
    { word: "cook", meaning: "煮；廚師" },
    { word: "hood", meaning: "兜帽" },
    { word: "hook", meaning: "鉤子" },
    { word: "hoop", meaning: "環；圈" },
    { word: "moose", meaning: "駝鹿" },
    { word: "pool", meaning: "水池" },
    { word: "school", meaning: "學校" },
    { word: "shook", meaning: "搖動（shake 的過去式）" },
    { word: "spoon", meaning: "湯匙" },
    { word: "stood", meaning: "站立（stand 的過去式）" },
    { word: "stool", meaning: "凳子" },
    { word: "cause", meaning: "原因；引起" },
    { word: "claw", meaning: "爪子" },
    { word: "crawl", meaning: "爬行" },
    { word: "draw", meaning: "畫；拉" },
    { word: "faucet", meaning: "水龍頭" },
    { word: "fawn", meaning: "小鹿" },
    { word: "laundry", meaning: "洗衣" },
    { word: "paw", meaning: "腳掌" },
    { word: "sauce", meaning: "醬汁" },
    { word: "shawl", meaning: "披肩" },
    { word: "straw", meaning: "吸管；稻草" },
    { word: "yawn", meaning: "打呵欠" },
    { word: "behind", meaning: "在⋯後面" },
    { word: "berry", meaning: "漿果" },
    { word: "branches", meaning: "樹枝" },
    { word: "bushy tail", meaning: "毛茸茸的尾巴" },
    { word: "dance", meaning: "跳舞" },
    { word: "flag", meaning: "旗子" },
    { word: "insect", meaning: "昆蟲" },
    { word: "quick", meaning: "快速的" },
    { word: "skunk", meaning: "臭鼬" },
    { word: "suddenly", meaning: "突然地" }
  ]
};
window.WEEK_LISTS = {
  ...window.WEEK_LISTS,

  13: [
    { word: "blew", meaning: "吹（blow 的過去式）" },
    { word: "chew", meaning: "咀嚼" },
    { word: "dew", meaning: "露水" },
    { word: "few", meaning: "少數的" },
    { word: "flew", meaning: "飛（fly 的過去式）" },
    { word: "grew", meaning: "成長（grow 的過去式）" },
    { word: "jewelry", meaning: "珠寶" },
    { word: "mew", meaning: "貓叫聲" },
    { word: "new", meaning: "新的" },
    { word: "screw", meaning: "螺絲" },
    { word: "stew", meaning: "燉菜" },
    { word: "threw", meaning: "丟（throw 的過去式）" },
    { word: "art", meaning: "藝術" },
    { word: "yard", meaning: "院子" },
    { word: "barn", meaning: "穀倉" },
    { word: "park", meaning: "公園" },
    { word: "hard", meaning: "困難的；硬的" },
    { word: "cart", meaning: "手推車" },
    { word: "dark", meaning: "黑暗的" },
    { word: "farm", meaning: "農場" },
    { word: "shark", meaning: "鯊魚" },
    { word: "sharp", meaning: "銳利的" },
    { word: "harm", meaning: "傷害" },
    { word: "alarm", meaning: "警報" },
    { word: "arms", meaning: "手臂" },
    { word: "march", meaning: "行進；三月" },
    { word: "smart", meaning: "聰明的" },
    { word: "buzzing", meaning: "嗡嗡聲" },
    { word: "careful", meaning: "小心的" },
    { word: "fur", meaning: "毛皮" },
    { word: "hit", meaning: "打；擊中" },
    { word: "hole", meaning: "洞" },
    { word: "honey", meaning: "蜂蜜" },
    { word: "lick", meaning: "舔" },
    { word: "path", meaning: "小路" },
    { word: "sting", meaning: "刺；叮" },
    { word: "stuck", meaning: "卡住的" },
    { word: "against", meaning: "反對；靠著" },
    { word: "hardly", meaning: "幾乎不" },
    { word: "meadow", meaning: "草地" },
    { word: "middle", meaning: "中間" },
    { word: "pit-pat", meaning: "滴答聲（如雨聲）" },
    { word: "space", meaning: "空間；太空" },
    { word: "toss", meaning: "投擲" },
    { word: "touch", meaning: "觸摸" },
    { word: "whistle", meaning: "吹口哨" }
  ],

  15: [
    { word: "baby", meaning: "嬰兒" },
    { word: "bunny", meaning: "小兔子" },
    { word: "city", meaning: "城市" },
    { word: "cry", meaning: "哭泣" },
    { word: "dry", meaning: "乾的" },
    { word: "fly", meaning: "飛" },
    { word: "fry", meaning: "油炸" },
    { word: "happy", meaning: "快樂的" },
    { word: "party", meaning: "派對" },
    { word: "pony", meaning: "小馬" },
    { word: "silly", meaning: "愚蠢的" },
    { word: "sky", meaning: "天空" },
    { word: "story", meaning: "故事" },
    { word: "chain", meaning: "鏈子" },
    { word: "chop", meaning: "砍；剁" },
    { word: "shed", meaning: "小屋；棚" },
    { word: "shelf", meaning: "架子" },
    { word: "thick", meaning: "厚的" },
    { word: "thin", meaning: "瘦的；薄的" },
    { word: "think", meaning: "思考" },
    { word: "thread", meaning: "線" },
    { word: "three", meaning: "三" },
    { word: "throat", meaning: "喉嚨" },
    { word: "whale", meaning: "鯨魚" },
    { word: "wheel", meaning: "輪子" },
    { word: "shines", meaning: "發光（shine 的第三人稱）" },
    { word: "through", meaning: "穿過" },
    { word: "bouncing", meaning: "彈跳" },
    { word: "spider", meaning: "蜘蛛" },
    { word: "webs", meaning: "蜘蛛網" },
    { word: "woods", meaning: "樹林" },
    { word: "glass", meaning: "玻璃" },
    { word: "tied together", meaning: "綁在一起" },
    { word: "drop", meaning: "滴下；掉落" },
    { word: "straight", meaning: "筆直的" },
    { word: "friendly", meaning: "友善的" },
    { word: "bless", meaning: "祝福" },
    { word: "blink", meaning: "眨眼" },
    { word: "crawl", meaning: "爬行" },
    { word: "flat", meaning: "平的" },
    { word: "follow", meaning: "跟隨" },
    { word: "join", meaning: "加入" },
    { word: "rock", meaning: "岩石；搖動" },
    { word: "star", meaning: "星星" },
    { word: "swish", meaning: "嗖嗖聲；揮動聲" }
  ]
};
window.WEEK_LISTS = {
  ...window.WEEK_LISTS,

  16: [
    { word: "bath", meaning: "洗澡" },
    { word: "bench", meaning: "長椅" },
    { word: "branch", meaning: "樹枝" },
    { word: "brush", meaning: "刷子" },
    { word: "dish", meaning: "盤子" },
    { word: "ditch", meaning: "溝渠" },
    { word: "path", meaning: "小徑" },
    { word: "ring", meaning: "戒指；鈴聲" },
    { word: "swing", meaning: "盪鞦韆" },
    { word: "switch", meaning: "開關；轉換" },
    { word: "teeth", meaning: "牙齒" },
    { word: "watch", meaning: "手錶；觀看" },
    { word: "bird", meaning: "鳥" },
    { word: "more", meaning: "更多" },
    { word: "shirt", meaning: "襯衫" },
    { word: "horse", meaning: "馬" },
    { word: "first", meaning: "第一" },
    { word: "for", meaning: "為了" },
    { word: "girl", meaning: "女孩" },
    { word: "horn", meaning: "角；喇叭" },
    { word: "dirt", meaning: "泥土" },
    { word: "short", meaning: "短的" },
    { word: "store", meaning: "商店" },
    { word: "morning", meaning: "早晨" },
    { word: "dinosaur", meaning: "恐龍" },
    { word: "third", meaning: "第三" },
    { word: "whirl", meaning: "旋轉" },
    { word: "appear", meaning: "出現" },
    { word: "decide", meaning: "決定" },
    { word: "furry", meaning: "毛茸茸的" },
    { word: "sister", meaning: "姐妹" },
    { word: "strange", meaning: "奇怪的" },
    { word: "tease", meaning: "取笑；逗弄" }
  ],

  17: [
    { word: "barn", meaning: "穀倉" },
    { word: "card", meaning: "卡片" },
    { word: "dart", meaning: "飛鏢；猛衝" },
    { word: "fern", meaning: "蕨類植物" },
    { word: "harp", meaning: "豎琴" },
    { word: "ladder", meaning: "梯子" },
    { word: "letter", meaning: "信件；字母" },
    { word: "number", meaning: "數字" },
    { word: "paper", meaning: "紙張" },
    { word: "shark", meaning: "鯊魚" },
    { word: "slipper", meaning: "拖鞋" },
    { word: "water", meaning: "水" },
    { word: "yard", meaning: "院子" },
    { word: "flutter", meaning: "拍動；飄動" },
    { word: "flyer", meaning: "傳單" },
    { word: "minute", meaning: "分鐘" },
    { word: "nearby", meaning: "附近" },
    { word: "reach", meaning: "到達；伸手" },
    { word: "seem", meaning: "似乎" },
    { word: "throat", meaning: "喉嚨" },
    { word: "hummingbird", meaning: "蜂鳥" },
    { word: "afraid", meaning: "害怕的" },
    { word: "exclaimed", meaning: "驚呼；喊叫" },
    { word: "frightened", meaning: "受驚嚇的" },
    { word: "lift", meaning: "抬起；電梯" },
    { word: "shut", meaning: "關閉" },
    { word: "stretch", meaning: "伸展" },
    { word: "wide", meaning: "寬的" }
  ],

  18: [
    { word: "cork", meaning: "軟木塞" },
    { word: "corn", meaning: "玉米" },
    { word: "dirt", meaning: "泥土" },
    { word: "fork", meaning: "叉子" },
    { word: "horn", meaning: "角；喇叭" },
    { word: "shirt", meaning: "襯衫" },
    { word: "short", meaning: "短的" },
    { word: "skirt", meaning: "裙子" },
    { word: "squirt", meaning: "噴射" },
    { word: "stir", meaning: "攪拌" },
    { word: "storm", meaning: "暴風雨" },
    { word: "third", meaning: "第三" },
    { word: "thorn", meaning: "刺；荊棘" },
    { word: "burn", meaning: "燃燒" },
    { word: "curb", meaning: "抑制；人行道邊" },
    { word: "curl", meaning: "捲曲" },
    { word: "fur", meaning: "毛皮" },
    { word: "hurt", meaning: "受傷" },
    { word: "turn", meaning: "轉動" },
    { word: "does", meaning: "做（do 的第三人稱）" },
    { word: "were", meaning: "是（be 動詞過去式）" },
    { word: "every", meaning: "每一個" },
    { word: "very", meaning: "非常" },
    { word: "give", meaning: "給" },
    { word: "live", meaning: "生活；居住" },
    { word: "thing", meaning: "東西；事情" },
    { word: "your", meaning: "你的" },
    { word: "many", meaning: "許多的" },
    { word: "who", meaning: "誰" },
    { word: "any", meaning: "任何的" },
    { word: "away", meaning: "離開" },
    { word: "goes", meaning: "去（go 的第三人稱）" },
    { word: "find", meaning: "找到" },
    { word: "kind", meaning: "親切的；種類" },
    { word: "ago", meaning: "以前" },
    { word: "another", meaning: "另一個" },
    { word: "corner", meaning: "角落" },
    { word: "everywhere", meaning: "到處" },
    { word: "fold", meaning: "摺疊" },
    { word: "important", meaning: "重要的" },
    { word: "mouse", meaning: "老鼠" },
    { word: "neck", meaning: "脖子" },
    { word: "owl", meaning: "貓頭鷹" },
    { word: "sharp", meaning: "銳利的" },
    { word: "size", meaning: "尺寸" },
    { word: "supper", meaning: "晚餐" },
    { word: "argue", meaning: "爭論" },
    { word: "bright", meaning: "明亮的" },
    { word: "button", meaning: "按鈕；鈕扣" },
    { word: "chuckle", meaning: "輕笑" },
    { word: "important", meaning: "重要的" },
    { word: "ladybug", meaning: "瓢蟲" },
    { word: "prettiest", meaning: "最漂亮的" },
    { word: "shout", meaning: "喊叫" },
    { word: "spots", meaning: "斑點" },
    { word: "whole", meaning: "全部的" }
  ]
};
